# File: .github/workflows/setup-node/action.yml
# - Cache dependencies âš¡
name: setup-node
description: "Setup Node.js âš™ï¸ - Install dependencies ğŸ”§"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js âš™ï¸
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # - name: Cache dependencies âš¡
    #   id: cache_dependencies
    #   uses: actions/cache@v3
    #   with:
    #     path: node_modules
    #     key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies ğŸ”§
      run: npm install
      # if: steps.cache_dependencies.outputs.cache-hit != 'true'
      # run: npm ci